### ISSUE TITLE
Having issues pushing to WP Engine

### ISSUE THREAD

**Issue by TatsumiSuenaga** [jovrtn/github-action-wpengine-git-deploy#1]
I'm getting this issue
```
error: src refspec master does not match any.
error: failed to push some refs to 'git@git.wpengine.com:production/stagingenv.git'
```
I've tried changing my private and public rsa keys (the one that currently works when I push, and a deploy specific one). 

Could it be an issue with my private key? All I do is `pbcopy < ~/.ssh/id_rsa` to get my private key.

Also, below is an example of my workflow `yml`.

```
name: Staging CI

on:
  push:
    branches: [ staging ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: GitHub Action for WP Engine Git Deployment
      uses: jovrtn/github-action-wpengine-git-deploy@0.1.2
      env:
        WPENGINE_ENVIRONMENT_NAME: stagingenv
        WPENGINE_SSH_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        WPENGINE_SSH_KEY_PUBLIC: ${{ secrets.WPENGINE_SSH_KEY_PUBLIC }}
```
